baseURL = "//mshjri.com"
languageCode = "en-us"
title = "Omar Al-Mashjari"
theme = "minimist"

copyright = "Copyright © 2018, Omar AlMashjari; all rights reserved."

pluralizeListTitles = false

[params]
    websiteTitle = "Omar Almashjari" # used on homepage and navigation
    Description = "Front End Web Developer."
    email = "omar.mshjri@gmail.com"


    # Homepage brief
    enableHomepageBlogBrief = true
    briefSection = "blog" # specify a section to show links from (default: "" (blank), will list recent pages from all sections)
    numberOfBriefLinks = 4
    more = "More"
    
    # footer
    showMinimistCredits = true


[[params.navigation]]
# navigation links
# [ [name, URL ], [hideOnMobile, hideOnItsOwnPage] ]
# hideOnMobile: will hide the link on screens smaller than 600px wide (default: false)
# hideItsOwnPage: will hide the navigation link for a page on the page itself (ex: hide 'about' link on the about page) (default: true)
    nav = [
        [ [ "Home", "/"], [false, true] ], # todo test the / if not then create and if statement and .baseurl 
        [ [ "Portfolio", "https://portfolio.mshjri.com"], [false, true] ],
        [ [ "Blog", "/blog/"], [false, false] ],
        [ [ "About", "/about/"], [false, true] ],
        [ [ "RSS", ""], [true, true] ], # rss url will be provided by default
        # add more links if needed
    ]

[social]
    Github = "https://github.com/codezarsenal"
    Medium = "https://medium.com/@codezarsenal"
    Twitter = "https://twitter.com/mshjrii"